# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d588e829ab04c034e3670aa295a168457d5f7c1a8b0dae9ab57a92f8fbca6038b3e5fcde5875cb6c97827b471a9e5e8e07b8c37ec4c41e0351f205218de6877e

test:
  secret_key_base: 0d2a43996350c595ee4e8a3ad4fba3f54789e1438582c63ab8749faf821b2765d51a228215caea98c4d0e0a7809b25102e11581ec912ab87f042944d9adf37a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
